Vagrant.configure("2") do |config|
  config.vm.define "db" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.network "private_network", ip: "192.168.10.150"
    db.vm.synced_folder ".", "/home/vagrant/app"
    db.vm.provision :shell, path: "db/db_updates.sh"
  end  
  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/xenial64"
    # creating a virtual machine ubuntu
    # assign private ip to our VM
    app.vm.network "private_network", ip: "192.168.10.100"
    # Ensure to install hostsupdater plugin on local host before rerunning vagrant
    config.hostsupdater.aliases = ["development.local"]
    # sync folder from OS to VM
                    # "." means current location - into VM
    app.vm.provision :shell, path: "app/update_tests.sh"
    app.vm.synced_folder ".", "/home/vagrant/app"
  end
end  